### ISSUE TITLE
Refreshing page many times makes tasks unavailable

### ISSUE THREAD

**Issue by OttoTarkka** [TurkuNLP/Open-Assistant#6]
After repeatedly refreshing the page, all the tasks become unavailable. The start page says, for example, "5 tehtävää saatavilla" but when cliking on a task to start it, it tells me "Uusia tehtäviä ei löytynyt."

**Comment by luukkonenr** [comment]
This happens, because each time a page is refreshed / user is given a new task, the task is marked as that users property. One user can hold N (=8) simultaneous tasks. After a short while these tasks expire and user can get more tasks. This is a feature in the original repo.
